config/routes.rb
Rails.application.routes.draw do
  get "/index", to: "pruebas#index"
  get "/principal", to: "pruebas#principal", as: "principal"
  get "/sitios", to: "pruebas#sitios", as: "sitios"
  get "/contacto", to: "pruebas#contacto", as: "contacto"
  get "/clientes", to: "pruebas#clientes", as: "clientes"
  get "/comencemos", to: "pruebas#comencemos", as: "comencemos"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pruebas_controller.rb
class PruebasController < ApplicationController
    
    def index
        
    end
    def principal
        
    end
    def sitios
        
    end
    def contacto
        
    end
    def clientes
        
    end
    def comencemos
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Studio BAD DOG</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# Bootstrap %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%# Iconos de Bootstrap %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <%# Javascript %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'main' %>
    <%# Fuentes de Google %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@500&display=swap" rel="stylesheet">
    <%# Favicon %>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%# hojas de estilos propios%>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'shared/header'%>
    <%= yield %>
    <%= render 'shared/footer'%>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pruebas/clientes.html.erb
<main class="pt-5 bg-color">
   <div class="container">
    <section class="row g-0">
      <article class="col-12 text-center">
        <h1>Clientes & Colaboraciones</h1>
        <p class="fs-5">Aquí hay una selección de clientes felices y hermosos proyectos.</p>
      </article>
      <article class="col-12">
        <div class="card text-bg-dark border-0 rounded-0">
          <%= image_tag("clients-1", class: "card-img", alt: "logo") %>
          <div class="card-img-overlay bg-second-alpha-color d-flex flex-column justify-content-md-center">
            <h5 class="card-title">Andy Pandharklar</h5>
            <p class="card-text">
             <small>CEO/Co-fundador, Commerce Ai</small>
              <br>
              <a class="text-success" data-bs-toggle="modal" data-bs-target="#cliente-1" href="#">Ver Proyecto</a> 
            </p>
            <p class="card-text">
              <blockquote class="d-none d-md-block">
                 No estábamos satisfechos con ninguna de nuestras opciones anteriores. Pero Bad Dog tuvo lo que teníamos en mente.
              </blockquote>
            </p>
          </div>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="cliente-1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title fs-5" id="exampleModalLabel">Commerce Ai</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <p>
                  Posicioné una nueva marca comercial (en línea) y diseñé un sitio web adaptado y hecho a medida.
                </p>
                <%= image_tag("work-layout-1", class: "img-fluid", alt: "Commerce Ai") %>
              </div>
            </div>
          </div>
        </div>
      </article>
      <article class="col-12 col-sm-6 col-lg-4">
          <div class="card text-bg-dark border-0 rounded-0">
          <%= image_tag("clients-2", class: "card-img", alt: "logo") %>
          <div class="card-img-overlay bg-second-alpha-color d-flex flex-column justify-content-md-center">
            <h5 class="card-title">Zeb Couch</h5>
            <p class="card-text">
             <small>Dueño de Zeb Couch</small>
              <br>
               <a class="text-success" data-bs-toggle="modal" data-bs-target="#cliente-2" href="#">Ver Proyecto</a> 
            </p>
            <p class="card-text">
              <blockquote class="d-none d-md-block">
                 Trabajé con Bad Dog en varios proyectos y trabajaré con ellos siempre que pueda.
              </blockquote>
            </p>
          </div>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="cliente-2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title fs-5" id="exampleModalLabel">Walkers</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <p>
                  He estado trabajando con Zeb en varios otros proyectos el ultimo año. Cuando se contactó conmigo para hablar sobre un proyecto que se desarrollaba en torno al diseño de una tienda web inmediatamente me interesé y me inspiré.
                </p>
                <%= image_tag("work-layout-2", class: "img-fluid", alt: "Commerce Ai") %>
              </div>
            </div>
          </div>
        </div>
      </article>
      <article class="col-12 col-sm-6 col-lg-4">
        <div class="card text-bg-dark border-0 rounded-0">
          <%= image_tag("clients-3", class: "card-img", alt: "logo") %>
          <div class="card-img-overlay bg-second-alpha-color d-flex flex-column justify-content-md-center">
            <h5 class="card-title">Lori Knisely</h5>
            <p class="card-text">
             <small>subgerente de hey textile</small>
              <br>
              <a class="text-success"href="#">Ver Proyecto</a> 
            </p>
            <p class="card-text">
              <blockquote class="d-none d-md-block">
                 Bad Dog siempre lo consigue!
              </blockquote>
            </p>
          </div>
        </div>
      </article>
      <article class="col-12 col-sm-6 col-lg-4">
          <div class="card text-bg-dark border-0 rounded-0">
          <%= image_tag("clients-4", class: "card-img", alt: "logo") %>
          <div class="card-img-overlay bg-second-alpha-color d-flex flex-column justify-content-md-center">
            <h5 class="card-title">Tom Allan</h5>
            <p class="card-text">
             <small>Director Basis Network</small>
              <br>
              <a class="text-success"href="#">Ver Proyecto</a> 
            </p>
            <p class="card-text">
              <blockquote class="d-none d-md-block">
                 Definitivamente contrataremos los servicios de Bad Dog para proyectos futuros
              </blockquote>
            </p>
          </div>
        </div>
      </article>
      <article class="col-12 col-sm-6 col-lg-4">
        <div class="card text-bg-dark border-0 rounded-0">
          <%= image_tag("clients-5", class: "card-img", alt: "logo") %>
          <div class="card-img-overlay bg-second-alpha-color d-flex flex-column justify-content-md-center">
            <h5 class="card-title">Jin Choeh</h5>
            <p class="card-text">
             <small>Co-fundador Swingvy</small>
              <br>
              <a class="text-success"href="#">Ver Proyecto</a> 
            </p>
            <p class="card-text">
              <blockquote class="d-none d-md-block">
                 Bad Dog estuvo mas allá de nuestras expectativas.
              </blockquote>
            </p>
          </div>
        </div>
      </article>
      <article class="col-12 col-sm-6 col-lg-4">
        <div class="card text-bg-dark border-0 rounded-0">
          <%= image_tag("clients-6", class: "card-img", alt: "logo") %>
          <div class="card-img-overlay bg-second-alpha-color d-flex flex-column justify-content-md-center">
            <h5 class="card-title">Jennifer Blair</h5>
            <p class="card-text">
             <small>CEO de Lash SPA Studio</small>
              <br>
              <a class="text-success"href="#">Ver Proyecto</a> 
            </p>
            <p class="card-text">
              <blockquote class="d-none d-md-block">
                Hemos encontrado un socio perfecto para nuestras necesidades de diseño y marca.   
              </blockquote>
            </p>
          </div>
        </div>
      </article>
      <article class="col-12 col-sm-6 col-lg-4">
        <div class="card text-bg-dark border-0 rounded-0">
          <%= image_tag("clients-7", class: "card-img", alt: "logo") %>
          <div class="card-img-overlay bg-second-alpha-color d-flex flex-column justify-content-md-center">
            <h5 class="card-title">Sietse Kingma</h5>
            <p class="card-text">
             <small>Co-fundador BambuuVB</small>
              <br>
              <a class="text-success"href="#">Ver Proyecto</a> 
            </p>
            <p class="card-text">
              <blockquote class="d-none d-md-block">
                 Bad Dog crea sitios impresionantes, estrategias increibles y mucho más.
            </p>
          </div>
        </div>
      </article>
      <article class="col-12">
        <div class="card text-bg-dark border-0 rounded-0">
          <%= image_tag("clients-8", class: "card-img", alt: "logo") %>
          <div class="card-img-overlay bg-second-alpha-color d-flex flex-column justify-content-md-center bg-second-alpha-color d-flex flex-column justify-content-md-center">
            <h5 class="card-title">Sergi Magdalin</h5>
            <p class="card-text">
             <small>Co-fundador Webflow</small>
              <br>
              <a class="text-success"href="#">Ver Proyecto</a> 
            </p>
            <p class="card-text">
              <blockquote class="d-none d-md-block">
                 Bad Dog es una de las mejores empresas con las que eh trabajado.
              </blockquote>
            </p>
          </div>
        </div>
      </article>
    </section>

   </div>
</main>

app/views/pruebas/comencemos.html.erb
<main class="py-5 bg-color">
    <div class="container ">
          <article class="col-12 text-center">
            <h1>Comencemos tu nuevo proyecto</h1>
            <p class="fs-5">Me encanta la colaboración mutua entre <b>profesional y cliente</b>, prefiero la frase:</p>
            <p class="fs-2"> <b>"Trabajo contigo"</b></p>
            <p class="fs-5">en vez de: Trabajo para ti</p>
            <p class="text-start">Me gusta tener contacto directo con el cliente, lo que permite una comunicación clara y actualizaciones periódicas del proyecto, haciendo todo lo posible para no causar demoras, intento definir las características y experiencias más adecuadas que briden la misma satisfacción.</p>
            <p class="text-start">Me parece importante ofrecer a mis clientes una comprensión clara de lo que pueden y deben esperar de mí. Si trabajamos juntos en su sitio web, el proceso será como se describe a continuación</p>
          </article>
        <section class="row align-items-lg-center">
          <article class="col-12 col-lg-6 text-lg-end">
            <h2>Paso 1</h2>
            <h3>Concepto y Presupuesto</h3>
            <p>Discutimos las primeras ideas durante una breve reunion en sitio, por correo electrónico o video llamada. Siguiendo las ideas iniciales te presentaré un presupuesto oficial para el proyecto</p>  
          </article>
          <article class="col-12 col-lg-6">
            <%= image_tag("workflow-step-1", class: "", alt: "paso 1") %>
          </article>
        </section>
        <section class="row align-items-lg-center">
          <article class="col-12 col-lg-6 order-lg-1">
            <h2>Paso 2</h2>
            <h3>Propuesta de Diseño</h3>
            <p>Una vez que se firme y/o acepte la cotización recibirás la primera factura (50% del monto acordado) después del pago iniciaré el proyecto. Estudiaré tu empresa, producto o servicio. Para acelerar el proceso, es necesario que me entregues todo el material del proyecto en este momento. Logo, textos, fotos, mapa del sitio, etc. En 7 días te presentaré un diseño profesional y apropiado para tu sitio web</p>  
          </article>
          <article class="col-12 col-lg-6">
            <%= image_tag("workflow-step-2", class: "", alt: "paso 2") %>
          </article>
        </section>  
        <section class="row align-items-lg-center ">
          <article class="col-12 col-lg-6 text-lg-end">
            <h2>Paso 3</h2>
            <h3>Retroalimentación</h3>
            <p>Después de la primera presentación del diseño, puedes dar tu opinión y compartir comentarios. Tendrás un máximo de 2 rondas de comentarios.<sup class="text-first-color fw-bold">*</sup> De esta manera no nos detenemos en un círculo sin fin de cambios menores. Esto evita perder tiempo y presupuesto. Es importante compartir buenos comentarios*</p>  
          </article>
          <article class="col-12 col-lg-6">
            <%= image_tag("workflow-step-3", class: "", alt: "paso 3") %>
          </article>
        </section>
        <section class="row align-items-lg-center">
          <article class="col-12 col-lg-6 order-lg-1">
            <h2>Paso 4</h2>
            <h3>Acabado de diseño y contenido</h3>
            <p>Después de la última ronda de comentarios, haré los cambios finales y terminaré el diseño completamente. En consulta contigo, también se procesa el contenido final como textos y fotos.</p>  
          </article>
          <article class="col-12 col-lg-6">
            <%= image_tag("workflow-step-4", class: "", alt: "paso 4") %>
          </article>
        </section>
        <section class="row align-items-lg-center">
          <article class="col-12 col-lg-6 text-lg-end">
            <h2>Paso 5</h2>
            <h3>Fin del proyecto</h3>
            <p>Dependiendo de la complejidad del proyecto, se terminará de 2 a 8 semanas. Una vez finalizado recibirás la factura final (a menos que se acuerde de otra manera). Después del pago te enviaré una copia de todos los archivos originales y pondré en línea tu sitio. Después de esta etapa, los cambios menores y errores se procesarán de forma gratuita. Los cambios mayores tendrán costos adicionales.<sup class="text-first-color fw-bold">*</sup></p>  
          </article>
          <article class="col-12 col-lg-6">
            <%= image_tag("workflow-step-5", class: "", alt: "paso 5") %>
          </article>
        </section>
        <article class="col-12">
            <p class="text-center">
              <small><sup class="text-first-color fs-5 fw-bold">*</sup>
               Todo cambio adicional generará cargos extras. Tarifa por hora: <b>150usd + impuestos.</b>
              </small>
            </p>
        </article>
    </div>
</main>

app/views/pruebas/principal.html.erb
<main class="bg-gradient-blue-green pt-5">
  <div class="container">
    <section class="row text-white align-items-lg-center mb-5">
      <article class="col-12 col-lg-5">
        <h3>Necesitas un increíble sitio web?</h3>
        <p class="fs-5">Un sitio hermoso, moderno, responsivo y personalziado para tu compañia, negocio, marca, servicio o producto.</p>
        <a href="#servicios" class="btn btn-success btn-lg fw-bold" >Sí, Empecemos!</a>
      </article>
      <article class="col-12 col-lg-7">
        <%= image_tag("header-image.png", class: "img-fluid", alt: "Necesitas un increíble sitio web?") %>
      </article>
      <article class="col-12 col-lg-5 order-lg-1">
        <h2>Sitios web Responsivos</h2>
        <p class="fs-5">Un sitio hermoso, moderno, responsivo y personalziado para tu compañia, negocio, marca, servicio o producto.Es importante proporcionar a tus visitantes una experiencia web óptima en dispositivos móviles.El diseño web responsivo significa que tu sitio se adapta instantáneamente al dispositivo que el visitante utiliza. Mi trabajo es hacer que la visita de tus usuarios sea lo más agradable e intuitiva para ellos </p>
      </article>
      <article class="col-12 col-lg-7">
        <%= image_tag("header-image-2.png", class: "img-fluid", alt: "Sitios web Responsivos") %>
      </article>
    </section>
    <section id="servicios" class="row min-vh-100 align-items-lg-center">
      <article class="col-12 col-md-6 col-lg-3 d-flex">
        <div class="card mx-auto mb-3" style="width: 18rem;">
          <%= image_tag("icon-sites.png", class: "bg-third-color", alt: "Nuevo sitio Web") %>
          <div class="card-body">
          <h5 class="card-title">Nuevo Sitio Web</h5>
          <p class="card-text">Necesitas un nuevo sitio web 100% responsivo?</p>
          <%= link_to sitios_path, class: 'text-third' do %>
            Más Detalles
            <i class="bi bi-chevron-right"></i>
          <% end %>
          </div>
        </div>     
      </article>
      <article class="col-12 col-md-6 col-lg-3 d-flex">
        <div class="card mx-auto mb-3" style="width: 18rem;">
          <%= image_tag("icon-clients.png", class: "bg-third-color", alt: "Clients") %>
          <div class="card-body">
          <h5 class="card-title">Clientes</h5>
          <p class="card-text">Clientes Felices y proyectos hermosos</p>
          <%= link_to sitios_path, class: 'text-third' do %>
            Más Detalles
            <i class="bi bi-chevron-right"></i>
          <% end %>
          </div>
        </div>
      </article>
      <article class="col-12 col-md-6 col-lg-3 d-flex">
        <div class="card mx-auto mb-3" style="width: 18rem;">
          <%= image_tag("icon-workflow.png", class: "bg-third-color", alt: "Flujo de Trabajo") %>
          <div class="card-body">
          <h5 class="card-title">Flujo de Trabajo</h5>
          <p class="card-text">Escucho tus necesidades, Discutamos tu Proyecto</p>
          <%= link_to sitios_path, class: 'text-third' do %>
            Más Detalles
            <i class="bi bi-chevron-right"></i>
          <% end %>
          </div>
        </div>
      </article>
      <article class="col-12 col-md-6 col-lg-3 d-flex">
        <div class="card mx-auto mb-3" style="width: 18rem;">
          <%= image_tag("icon-about.png", class: "bg-third-color", alt: "Contacto") %>
          <div class="card-body">
          <h5 class="card-title">Contacto</h5>
          <p class="card-text">Interesado? comencemos con tu nuevo proyecto</p>
          <%= link_to sitios_path, class: 'text-third' do %>
            Más Detalles
            <i class="bi bi-chevron-right"></i>
          <% end %>
          </div>
        </div>
      </article>
    </section>
  </div>
</main>

app/views/pruebas/sitios.html.erb
<main class="pt-5 bg-color">
  <section id="ultimos-proyectos" class="pb-5">
    <div class="text-center">
      <h1>Sitios web 100% responsivos</h1>
      <p class="fs-5">
        Desarrollo sitios web de una sola página y de varias páginas
      </p>
    </div>
    <div id="carouselExample" class="carousel slide">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <%= image_tag("work-slide-1", class: "d-block w-100", alt: "Trabajo 1") %>  
        </div>
        <div class="carousel-item">
          <%= image_tag("work-slide-2", class: "d-block w-100", alt: "Trabajo 2") %> 
        </div>
        <div class="carousel-item">
          <%= image_tag("work-slide-3", class: "d-block w-100", alt: "Trabajo 3") %> 
        </div>
        <div class="carousel-item">
          <%= image_tag("work-slide-4", class: "d-block w-100", alt: "Trabajo 4") %> 
        </div>
        <div class="carousel-item">
          <%= image_tag("work-slide-5", class: "d-block w-100", alt: "Trabajo 5") %> 
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </section>
  <section id="single-page" class="min-vh-100 bg-hero-image" 
  style="--bg-image: url(<%= asset_path('site-singlepage.jpg') %>)" >
    <article class="bg-alpha-color min-vh-100 d-flex align-items-center">
        <div class="container">
          <article class="col-12 col-lg-6 offset-lg-6">
            <a href="/contacto" class="btn btn-success btn-lg text-white mb-5" >
              <b>Desde 400$ <small>USD</small></b>
            </a>
            <h2>Sitio de una sola página</h2>
            <small class="">El precio puede ser mas alto (o mas bajo) dependiendo de los requisitos de su proyecto</small>
            <p class="my-5 fs-5">Una sola página o página de destino es un sitio web que consta de una página. Perfecto para presentar a tu empresa, organización producto o servicio de una manera hermosa y moderna en Internet.</p>
            <%= link_to contacto_path, class: 'fw-bold fs-4' do %>
              Solicite una Cotización Ahora
              <i class="bi bi-chevron-right"></i>
            <% end %>
            <div class="row mt-5">
              <div class="col">
                 <p><i class="bi bi-check-lg"></i>Sitio web de una sola página</p>
                 <p><i class="bi bi-check-lg"></i>100% Responsivo</p>
                 <p><i class="bi bi-check-lg"></i>Diseño Personalizado</p>
              </div>
              <div class="col">
                 <p><i class="bi bi-check-lg"></i>Correción de Estilo</p>
                 <p><i class="bi bi-check-lg"></i>Edición de Imagenes</p>
                 <p><i class="bi bi-check-lg"></i>Soporte</p>
              </div>
            </div>
          </article>
    
        </div>
    </article>
  </section>
  <section id="multi-page" class="min-vh-100 bg-hero-image"
  style="--bg-image: url(<%= asset_path('site-multipage.jpg') %>)">
    <article class="bg-alpha-color min-vh-100 d-flex align-items-center">
        <div class="container">
          <article class="col-12 col-lg-6">
            <a href="/contacto" class="btn btn-success btn-lg text-white mb-5" >
              <b>Desde 1000$ <small>USD</small></b>
            </a>
            <h2>Sitio Multipágina</h2>
            <small class="">El precio puede ser mas alto (o mas bajo) dependiendo de los requisitos de su proyecto</small>
            <p class="my-5 fs-5"> Un sitio web de varias páginas consta de dos o más páginas. Este formato es útilsi tiene ciertos elementos que desea mantener separados por páginas y urls diferentes.</p>
            <%= link_to contacto_path, class: 'fw-bold fs-4' do %>
              Solicite una Cotización Ahora
              <i class="bi bi-chevron-right"></i>
            <% end %>
            <div class="row mt-5">
              <div class="col">
                 <p><i class="bi bi-check-lg"></i>2 a 6 páginas</p>
                 <p><i class="bi bi-check-lg"></i>100% Responsivo</p>
                 <p><i class="bi bi-check-lg"></i>Diseño Personalizado</p>
              </div>
              <div class="col">
                 <p><i class="bi bi-check-lg"></i>Correción de Estilo</p>
                 <p><i class="bi bi-check-lg"></i>Edición de Imagenes</p>
                 <p><i class="bi bi-check-lg"></i>Soporte</p>
              </div>
            </div>
          </article>
    
        </div>
    </article>
  </section>

</main>

app/views/shared/_footer.html.erb
  <footer class="bg-dark">
  <div class="container text-center">
  <nav class="d-flex justify-content-evenly pt-2">
    <a href="https://facebook.com" target="_blank"> <i class="bi bi-facebook fs-3"></i> </a>
    <a href="https://twitter.com" target="_blank"> <i class="bi bi-twitter fs-3"></i> </a>
    <a href="https://github.com" target="_blank"> <i class="bi bi-github fs-3"></i> </a>
    <a href="https://youtube.com" target="_blank"> <i class="bi bi-youtube fs-3"></i> </a>
    <a href="https://instagram.com" target="_blank"> <i class="bi bi-instagram fs-3"></i> </a>
    <a href="https://facebook.com/messages" target="_blank"> <i class="bi bi-messenger fs-3"></i> </a>
    <a href="https://whatsapp.com" target="_blank"> <i class="bi bi-whatsapp fs-3"></i> </a>
  </nav>
  <small class="text-white">&copy; 2023 Hecho con fines educativos, tomando inspiración del sitio Corvus</small>
  </footer>
  </div>

app/views/shared/_header.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to principal_path, class: 'navbar-brand' do %>
      <%= image_tag("bad-dog-studio-logo.png", class: "navbar-brand", alt: "Studio BADDOG") %>
    <% end %>
    <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ms-lg-auto">
        <li class="nav-item">
          <%= link_to 'Inicio', principal_path, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Sitios
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/sitios#ultimos-proyectos">Últimos Proyectos</a></li>
            <li><a class="dropdown-item" href="/sitios#single-page">Single Page</a></li>
            <li><a class="dropdown-item" href="/sitios#multi-page">Multi Page</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/clientes">Clientes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/comencemos">Comencemos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/contacto">Interesado?</a>
        </li>

      </ul>
    </div>
  </div>
</nav>